### ISSUE TITLE
Update the text fields of all cards to give traits provided in square brackets

### ISSUE THREAD

**Issue by ACG8** [sIKE23/Mage-Wars#146] opened 2015-01-09 00:30 UTC
At the moment, coding for detection of traits means going through the list of all attached cards and giving traits based on the names of the cards (e.g. 'Storm Drake Hide' means +2 armor). It would be a lot easier if each card had as a property a list containing all the traits that it granted to the card to which it was attached (call it AttachTraits or something). Obviously, this would require going through the card data files for every set existing and putting in this property, but it would pay off in the long term by dramatically reducing the amount of maintenance when adding a new set.

**Comment by sIKE23** [comment] 2015-01-09 01:06
Most cards that grant these traits have in the "Text" Field the trait in
Square Brackets. So open up the SBB and in the search field, select Text
and then use a "[" as the search term.

Now there are items that are straight forward, ie armor +1 = [Armor +1] and
then there are the All (Friendly/Enemy) creatures in the zone gain Armor
+1, I have never come up with a good solution.

I am not that opposed to adding in a new field if needed. But I was
thinking it would be ok to leave it as is and add a [AttachTrait] into the
text field to meet this desired need. Then you could search in card.text
for [AttachTrait].

Further thoughts?

//FC

**Comment by anandaguneratne** [comment] 2015-01-09 01:33
Oh, that is a good idea. So you would leave it in the text field, but tag the desired traits?

So, for example, Barkskin, which currently reads

<property name="Text" value="Mage gains Armor +2 and Regenerate 2." />

Would be changed to

<property name="Text" value="Mage gains [Armor +2] and [Regenerate 2]." />

Right? We would also need to change the parsing script for proxy generation to eliminate the brackets, but that is easy.

**Comment by anandaguneratne** [comment] 2015-01-09 01:35
Oh, I see that this is already implemented

**Comment by anandaguneratne** [comment] 2015-01-09 01:37
We will still need to update a lot of cards, though. Not all traits are represented.

**Comment by anandaguneratne** [comment] 2015-01-09 01:43
So, for instance, we want

\<property name="Text" value="Mage gains Armor +2 and Regenerate 2." />

To become:

\<property name="Text" value="Mage gains Armor +2 and Regenerate 2.&#xD;&#xA;[+2 Armor] [Regenerate 2]" />

**Comment by sIKE23** [comment] 2015-01-09 02:18
Right I have been slowly filling in that data, the problem is on group effects, how would you represent them? [GroupTrait] [Friendly] [Armor +1]

Do we need to go back and change plain old Armor +1 [IndividualTrait] [Armor +1]

<property name="Text" value="Mage gains Armor +2 and Regenerate.&#xD;&#xA;[+2 Armor] [Regenerate 2]" />

Is correct....

**Comment by anandaguneratne** [comment] 2015-01-09 02:21
For now, we don't. We have no way to represent group effects anyway, since zones are not defined. We should just focus on individual effects.

**Comment by sIKE23** [comment] 2015-01-09 02:32
Any update to card data should be logged against #137

**Comment by anandaguneratne** [comment] 2015-01-09 02:43
All right, got it.

**Comment by anandaguneratne** [comment] 2015-01-11 09:10
One formatting note:

I am building a function that looks at a card and calculates all of the traits it has. I also want to consider traits that are given to the attack on a card. For this purpose, I would like to treat traits like Piercing and Vampiric that modify attacks as traits possessed by creatures.

For instance, I would like Lion Savagery to give the Piercing +1 trait to the creature, rather than to its attacks. This way, when calculating the piercing value of the attack, I can just check the attack's inherent piercing and the piercing trait on the creature, and add them together. I think this is the simplest way to do this. So you can label such cards with things like [Piercing +X] and [Vampirism], because we won't get confused anyway (since there are no traits that can be found both in an attack bar and on an object.

**Comment by anandaguneratne** [comment] 2015-01-11 09:50
Also, for the sake of uniform parsing, we have a problem with things like fireshaper ring that are labeled [Flame] [Melee +1] [Ranged +1]. It would be better to make up a trait, such as [Flame Attack +1]. Or, better yet (as I will note below), not even have a trait at all for non-standard bonuses. Otherwise, we can only compute such traits when actually declaring an attack, and I want to centralize the trait parsing functions. In any case, we need to decide on standardized ways to denote this. 

I think for unique, one-off abilities we might not need a trait. For example, for fireshaper ring, there is no other ability that boosts only flame attacks, so let's get rid of that trait all together. Only tag traits that are listed in the codex. Otherwise, we are bound to run into problems down the road. Better to just code specific exceptions (since we will have to do that anyway for each unique trait that we define). I would rather tell the program what to do if there is a Fireshaper Ring attached to the mage than tell it what to do if [Flame] comes before [Melee +1]

**Comment by sIKE23** [comment] 2015-01-11 17:16
I have written a function that looks for the name of a trait you passed it already, getTraitValue it is used to Automate Upkeep and Channeling at this point. I don't know how useful it would/will be to you, but it is there. Do what you would like with it if need be but 

I am not sure of what the issue is with Fireshaper ring and all there of the items you refer to are in the codex. There is nothing in the codex that says [Flame Attack +1]. What Cosworth, Lettucemode, and I were shooting for was leveraging the data generically.  If [Flame] is not a value that is parseable then lets do something like [DamType=Flame] that way when we get a Water Shaper ring (just joking but you get the point) the logic is there to support it generically.

For Enchantments that boost creatures traits, what I was thinking was that we would enforce the card.Target trait long term and then we could just apply the traits to the target.  Does that make any sense at all?

**Comment by anandaguneratne** [comment] 2015-01-12 00:41
Your getTraitValue function works for some things; I just want to make something more general that can read any trait.

[Flame] is parseable, the problem is that [Flame] [Melee +1] is easy to read as Flame,Melee +1. I could probably work with that (using the same method that I used to detect d12 effect rolls), but I don't think this is necessary, because there are so few cards that boost only one damage type. At some point in the future, we may want to add a more generic method for reading things like damage specific traits, but at the moment the amount of code we would need to add is the same if not more than simply searching for the fireshaper ring (or other similar rings). So my preference is to remove bracketed traits from such cards and search for the card itself by name.

Regarding enchantments, the function I am writing is designed to take care of the applying of traits to the target of an enchantment, though what it does is to look at the target and find all enchantments that give it a bonus. And I agree that eventually we will want to enforce card.Target.

**Comment by sIKE23** [comment] 2015-02-11 06:58
Where are we on this?

**Comment by anandaguneratne** [comment] 2015-02-11 12:49
I've done some work on this, but many of the cards still lack traits. Probably would be best if I take care of this.

**Comment by sIKE23** [comment] 2015-02-11 23:13
Should I move this issue to Long Term projects so we can mark against it as
we go?

**Comment by anandaguneratne** [comment] 2015-02-11 23:39
Sure.

**Comment by anandaguneratne** [comment] 2015-02-14 13:12
Okay, I think I've figured out how to implement zone buffs (and have begun to implement it); we do it the exact same way as targeted buffs, and let the card.target field dictate how it is interpreted. So if a card with card.target = 'Zone' has bracketed [Armor +2] (fortified position) or [Regenerate 1] (Mohktari), we assume that it is a zone buff. There won't be any conflicts, because zone-targeted spells almost always give their buff to everything in the zone, and object targeted spells almost always give their buff to only their target. There are some exceptions, such as Standard Bearer, but we can just hard-code those.

**Comment by anandaguneratne** [comment] 2015-02-14 13:26
Never mind; this won't work. Too many zone-targeted cards only give their buffs to specific types of cards. I'll have to just hard-code each zone-buff separately.

**Comment by ACG8** [comment] 2015-10-21 16:11
With the new buff encoding system, I think this issue is no longer relevant; in fact, I would like to migrate all of the traits out of the text fields and into the cBuffs field. Shall we close this issue?

**Comment by sIKE23** [comment] 2015-10-28 18:23
Closing

**Closed by sIKE23** 2015-10-28 18:23 UTC
Labels: Developer Tools
